/* The following code was generated by JFlex 1.7.0 */

import java_cup.runtime.*;

//-----------------------------------------------------------------------------

// The generated scanner will return a Symbol for each token that it finds.
// A Symbol contains an Object field named value; that field will be of type 
// TokenVal.
//
// A TokenVal object contains the line number on which the token occurs as
// well as the number of the character on that line that starts the token.
// Some tokens (e.g., literals) also include the value of the token.

//-----------------------------------------------------------------------------


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>simple.jlex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\4\1\2\1\56\1\57\1\57\1\56\16\4\4\0\1\2\1\21"+
    "\1\6\1\0\1\3\1\0\1\22\1\0\1\11\1\12\1\17\1\16"+
    "\1\13\1\5\1\40\1\20\12\1\1\0\1\15\1\24\1\14\1\25"+
    "\2\0\22\3\1\26\7\3\1\0\1\55\2\0\1\3\1\0\1\46"+
    "\1\45\1\47\1\50\1\36\1\51\1\33\1\54\1\31\2\3\1\44"+
    "\1\37\1\32\1\41\1\43\1\3\1\30\1\35\1\27\1\42\1\52"+
    "\1\53\1\3\1\34\1\3\1\7\1\23\1\10\1\0\6\4\1\60"+
    "\32\4\2\0\4\3\4\0\1\3\2\0\1\4\7\0\1\3\4\0"+
    "\1\3\5\0\27\3\1\0\37\3\1\0\u01ca\3\4\0\14\3\16\0"+
    "\5\3\7\0\1\3\1\0\1\3\21\0\160\4\5\3\1\0\2\3"+
    "\2\0\4\3\1\0\1\3\6\0\1\3\1\0\3\3\1\0\1\3"+
    "\1\0\24\3\1\0\123\3\1\0\213\3\1\0\5\4\2\0\246\3"+
    "\1\0\46\3\2\0\1\3\6\0\51\3\6\0\1\3\1\0\55\4"+
    "\1\0\1\4\1\0\2\4\1\0\2\4\1\0\1\4\10\0\33\3"+
    "\4\0\4\3\15\0\6\4\5\0\1\3\4\0\13\4\1\0\1\4"+
    "\3\0\53\3\37\4\4\0\2\3\1\4\143\3\1\0\1\3\10\4"+
    "\1\0\6\4\2\3\2\4\1\0\4\4\2\3\12\4\3\3\2\0"+
    "\1\3\17\0\1\4\1\3\1\4\36\3\33\4\2\0\131\3\13\4"+
    "\1\3\16\0\12\4\41\3\11\4\2\3\4\0\1\3\2\0\1\4"+
    "\30\3\4\4\1\3\11\4\1\3\3\4\1\3\5\4\22\0\31\3"+
    "\3\4\4\0\13\3\5\0\30\3\1\0\6\3\1\0\2\4\6\0"+
    "\10\4\52\3\72\4\66\3\3\4\1\3\22\4\1\3\7\4\12\3"+
    "\2\4\2\0\12\4\1\0\20\3\3\4\1\0\10\3\2\0\2\3"+
    "\2\0\26\3\1\0\7\3\1\0\1\3\3\0\4\3\2\0\1\4"+
    "\1\3\7\4\2\0\2\4\2\0\3\4\1\3\10\0\1\4\4\0"+
    "\2\3\1\0\3\3\2\4\2\0\12\4\4\3\7\0\2\3\1\0"+
    "\1\4\2\0\3\4\1\0\6\3\4\0\2\3\2\0\26\3\1\0"+
    "\7\3\1\0\2\3\1\0\2\3\1\0\2\3\2\0\1\4\1\0"+
    "\5\4\4\0\2\4\2\0\3\4\3\0\1\4\7\0\4\3\1\0"+
    "\1\3\7\0\14\4\3\3\1\4\13\0\3\4\1\0\11\3\1\0"+
    "\3\3\1\0\26\3\1\0\7\3\1\0\2\3\1\0\5\3\2\0"+
    "\1\4\1\3\10\4\1\0\3\4\1\0\3\4\2\0\1\3\17\0"+
    "\2\3\2\4\2\0\12\4\1\0\1\3\7\0\1\3\6\4\1\0"+
    "\3\4\1\0\10\3\2\0\2\3\2\0\26\3\1\0\7\3\1\0"+
    "\2\3\1\0\5\3\2\0\1\4\1\3\7\4\2\0\2\4\2\0"+
    "\3\4\7\0\3\4\4\0\2\3\1\0\3\3\2\4\2\0\12\4"+
    "\1\0\1\3\20\0\1\4\1\3\1\0\6\3\3\0\3\3\1\0"+
    "\4\3\3\0\2\3\1\0\1\3\1\0\2\3\3\0\2\3\3\0"+
    "\3\3\3\0\14\3\4\0\5\4\3\0\3\4\1\0\4\4\2\0"+
    "\1\3\6\0\1\4\16\0\12\4\11\0\1\3\6\0\5\4\10\3"+
    "\1\0\3\3\1\0\27\3\1\0\20\3\2\0\1\4\1\3\7\4"+
    "\1\0\3\4\1\0\4\4\7\0\2\4\1\0\3\3\2\0\1\3"+
    "\2\0\2\3\2\4\2\0\12\4\20\0\1\3\3\4\1\0\10\3"+
    "\1\0\3\3\1\0\27\3\1\0\12\3\1\0\5\3\2\0\1\4"+
    "\1\3\7\4\1\0\3\4\1\0\4\4\7\0\2\4\6\0\2\3"+
    "\1\0\2\3\2\4\2\0\12\4\1\0\2\3\1\4\14\0\4\4"+
    "\11\3\1\0\3\3\1\0\51\3\2\4\1\3\7\4\1\0\3\4"+
    "\1\0\4\4\1\3\5\0\3\3\1\4\7\0\3\3\2\4\2\0"+
    "\12\4\12\0\6\3\1\0\3\4\1\0\22\3\3\0\30\3\1\0"+
    "\11\3\1\0\1\3\2\0\7\3\3\0\1\4\4\0\6\4\1\0"+
    "\1\4\1\0\10\4\6\0\12\4\2\0\2\4\15\0\60\3\1\4"+
    "\2\3\7\4\4\0\10\3\10\4\1\0\12\4\47\0\2\3\1\0"+
    "\1\3\1\0\5\3\1\0\30\3\1\0\1\3\1\0\12\3\1\4"+
    "\2\3\11\4\1\3\2\0\5\3\1\0\1\3\1\0\7\4\1\0"+
    "\12\4\2\0\4\3\40\0\1\3\27\0\2\4\6\0\12\4\13\0"+
    "\1\4\1\0\1\4\1\0\1\4\4\0\2\4\10\3\1\0\44\3"+
    "\4\0\24\4\1\0\2\4\5\3\13\4\1\0\44\4\11\0\1\4"+
    "\71\0\53\3\24\4\1\3\12\4\6\0\6\3\4\4\4\3\3\4"+
    "\1\3\3\4\2\3\7\4\3\3\4\4\15\3\14\4\1\3\17\4"+
    "\2\0\46\3\1\0\1\3\5\0\1\3\2\0\53\3\1\0\u014d\3"+
    "\1\0\4\3\2\0\7\3\1\0\1\3\1\0\4\3\2\0\51\3"+
    "\1\0\4\3\2\0\41\3\1\0\4\3\2\0\7\3\1\0\1\3"+
    "\1\0\4\3\2\0\17\3\1\0\71\3\1\0\4\3\2\0\103\3"+
    "\2\0\3\4\40\0\20\3\20\0\126\3\2\0\6\3\3\0\u026c\3"+
    "\2\0\21\3\1\0\32\3\5\0\113\3\3\0\13\3\7\0\22\3"+
    "\4\4\11\0\23\3\3\4\13\0\22\3\2\4\14\0\15\3\1\0"+
    "\3\3\1\0\2\4\14\0\64\3\40\4\3\0\1\3\3\0\2\3"+
    "\1\4\2\0\12\4\41\0\17\4\6\0\131\3\7\0\5\3\2\4"+
    "\42\3\1\4\1\3\5\0\106\3\12\0\37\3\1\0\14\4\4\0"+
    "\14\4\12\0\12\4\36\3\2\0\5\3\13\0\54\3\4\0\32\3"+
    "\6\0\12\4\46\0\27\3\5\4\4\0\65\3\12\4\1\0\35\4"+
    "\2\0\13\4\6\0\12\4\15\0\1\3\10\0\16\4\1\0\20\4"+
    "\61\0\5\4\57\3\21\4\10\3\3\0\12\4\21\0\11\4\14\0"+
    "\3\4\36\3\15\4\2\3\12\4\54\3\16\4\14\0\44\3\24\4"+
    "\10\0\12\4\3\0\3\3\12\4\44\3\2\0\11\3\7\0\53\3"+
    "\2\0\3\3\20\0\3\4\1\0\25\4\4\3\1\4\6\3\1\4"+
    "\2\3\3\4\1\3\5\0\300\3\100\4\u0116\3\2\0\6\3\2\0"+
    "\46\3\2\0\6\3\2\0\10\3\1\0\1\3\1\0\1\3\1\0"+
    "\1\3\1\0\37\3\2\0\65\3\1\0\7\3\1\0\1\3\3\0"+
    "\3\3\1\0\7\3\3\0\4\3\2\0\6\3\4\0\15\3\5\0"+
    "\3\3\1\0\7\3\16\0\5\4\30\0\1\57\1\57\5\4\20\0"+
    "\2\3\23\0\1\3\13\0\5\4\1\0\12\4\1\0\1\3\15\0"+
    "\1\3\20\0\15\3\3\0\41\3\17\0\15\4\4\0\1\4\3\0"+
    "\14\4\21\0\1\3\4\0\1\3\2\0\12\3\1\0\1\3\3\0"+
    "\5\3\6\0\1\3\1\0\1\3\1\0\1\3\1\0\4\3\1\0"+
    "\13\3\2\0\4\3\5\0\5\3\4\0\1\3\21\0\51\3\u0a77\0"+
    "\345\3\6\0\4\3\3\4\2\3\14\0\46\3\1\0\1\3\5\0"+
    "\1\3\2\0\70\3\7\0\1\3\17\0\1\4\27\3\11\0\7\3"+
    "\1\0\7\3\1\0\7\3\1\0\7\3\1\0\7\3\1\0\7\3"+
    "\1\0\7\3\1\0\7\3\1\0\40\4\57\0\1\3\u01d5\0\3\3"+
    "\31\0\11\3\6\4\1\0\5\3\2\0\5\3\4\0\126\3\2\0"+
    "\2\4\2\0\3\3\1\0\132\3\1\0\4\3\5\0\53\3\1\0"+
    "\136\3\21\0\40\3\60\0\20\3\u0200\0\u19c0\3\100\0\u568d\3\103\0"+
    "\56\3\2\0\u010d\3\3\0\20\3\12\4\2\3\24\0\57\3\1\4"+
    "\4\0\12\4\1\0\37\3\2\4\120\3\2\4\45\0\11\3\2\0"+
    "\147\3\2\0\100\3\5\0\2\3\1\0\1\3\1\0\5\3\30\0"+
    "\20\3\1\4\3\3\1\4\4\3\1\4\27\3\5\4\4\0\1\4"+
    "\13\0\1\3\7\0\64\3\14\0\2\4\62\3\22\4\12\0\12\4"+
    "\6\0\22\4\6\3\3\0\1\3\1\0\2\3\13\4\34\3\10\4"+
    "\2\0\27\3\15\4\14\0\35\3\3\0\4\4\57\3\16\4\16\0"+
    "\1\3\12\4\6\0\5\3\1\4\12\3\12\4\5\3\1\0\51\3"+
    "\16\4\11\0\3\3\1\4\10\3\2\4\2\0\12\4\6\0\27\3"+
    "\3\0\1\3\3\4\62\3\1\4\1\3\3\4\2\3\2\4\5\3"+
    "\2\4\1\3\1\4\1\3\30\0\3\3\2\0\13\3\5\4\2\0"+
    "\3\3\2\4\12\0\6\3\2\0\6\3\2\0\6\3\11\0\7\3"+
    "\1\0\7\3\1\0\53\3\1\0\16\3\6\0\163\3\10\4\1\0"+
    "\2\4\2\0\12\4\6\0\u2ba4\3\14\0\27\3\4\0\61\3\u2104\0"+
    "\u016e\3\2\0\152\3\46\0\7\3\14\0\5\3\5\0\1\3\1\4"+
    "\12\3\1\0\15\3\1\0\5\3\1\0\1\3\1\0\2\3\1\0"+
    "\2\3\1\0\154\3\41\0\u016b\3\22\0\100\3\2\0\66\3\50\0"+
    "\15\3\3\0\20\4\20\0\20\4\3\0\2\3\30\0\3\3\31\0"+
    "\1\3\6\0\5\3\1\0\207\3\2\0\1\4\4\0\1\3\13\0"+
    "\12\4\7\0\32\3\4\0\1\3\1\0\32\3\13\0\131\3\3\0"+
    "\6\3\2\0\6\3\2\0\6\3\2\0\3\3\3\0\2\3\3\0"+
    "\2\3\22\0\3\4\4\0\14\3\1\0\32\3\1\0\23\3\1\0"+
    "\2\3\1\0\17\3\2\0\16\3\42\0\173\3\105\0\65\3\210\0"+
    "\1\4\202\0\35\3\3\0\61\3\17\0\1\4\37\0\40\3\15\0"+
    "\36\3\5\0\46\3\5\4\5\0\36\3\2\0\44\3\4\0\10\3"+
    "\1\0\5\3\52\0\236\3\2\0\12\4\6\0\44\3\4\0\44\3"+
    "\4\0\50\3\10\0\64\3\14\0\13\3\1\0\17\3\1\0\7\3"+
    "\1\0\2\3\1\0\13\3\1\0\17\3\1\0\7\3\1\0\2\3"+
    "\103\0\u0137\3\11\0\26\3\12\0\10\3\30\0\6\3\1\0\52\3"+
    "\1\0\11\3\105\0\6\3\2\0\1\3\1\0\54\3\1\0\2\3"+
    "\3\0\1\3\2\0\27\3\12\0\27\3\11\0\37\3\101\0\23\3"+
    "\1\0\2\3\12\0\26\3\12\0\32\3\106\0\70\3\6\0\2\3"+
    "\100\0\1\3\3\4\1\0\2\4\5\0\4\4\4\3\1\0\3\3"+
    "\1\0\35\3\2\0\3\4\4\0\1\4\40\0\35\3\3\0\35\3"+
    "\43\0\10\3\1\0\34\3\2\4\31\0\66\3\12\0\26\3\12\0"+
    "\23\3\15\0\22\3\156\0\111\3\67\0\63\3\15\0\63\3\15\0"+
    "\44\3\4\4\10\0\12\4\u0146\0\52\3\1\0\2\4\3\0\2\3"+
    "\113\0\3\4\35\3\12\0\1\3\10\0\26\3\13\4\37\0\22\3"+
    "\4\4\52\0\25\3\33\0\27\3\11\0\3\4\65\3\17\4\37\0"+
    "\13\4\2\3\2\4\1\3\11\0\4\4\55\3\13\4\2\0\1\4"+
    "\4\0\1\4\12\0\1\4\2\0\31\3\7\0\12\4\6\0\3\4"+
    "\44\3\16\4\1\0\12\4\4\0\1\3\2\4\1\3\10\0\43\3"+
    "\1\4\2\0\1\3\11\0\3\4\60\3\16\4\4\3\4\0\4\4"+
    "\1\0\14\4\1\3\1\0\1\3\43\0\22\3\1\0\31\3\14\4"+
    "\6\0\1\4\2\3\1\4\76\0\7\3\1\0\1\3\1\0\4\3"+
    "\1\0\17\3\1\0\12\3\7\0\57\3\14\4\5\0\12\4\6\0"+
    "\4\4\1\0\10\3\2\0\2\3\2\0\26\3\1\0\7\3\1\0"+
    "\2\3\1\0\5\3\1\0\2\4\1\3\7\4\2\0\2\4\2\0"+
    "\3\4\2\0\1\3\6\0\1\4\5\0\5\3\2\4\2\0\7\4"+
    "\3\0\5\4\213\0\65\3\22\4\4\3\5\0\12\4\4\0\1\4"+
    "\3\3\36\0\60\3\24\4\2\3\1\0\1\3\10\0\12\4\246\0"+
    "\57\3\7\4\2\0\11\4\27\0\4\3\2\4\42\0\60\3\21\4"+
    "\3\0\1\3\13\0\12\4\46\0\53\3\15\4\1\3\7\0\12\4"+
    "\66\0\33\3\2\0\17\4\4\0\12\4\6\0\7\3\271\0\54\3"+
    "\17\4\145\0\100\3\12\4\25\0\10\3\2\0\1\3\2\0\10\3"+
    "\1\0\2\3\1\0\30\3\6\4\1\0\2\4\2\0\4\4\1\3"+
    "\1\4\1\3\2\4\14\0\12\4\106\0\10\3\2\0\47\3\7\4"+
    "\2\0\7\4\1\3\1\0\1\3\1\4\33\0\1\3\12\4\50\3"+
    "\7\4\1\3\4\4\10\0\1\4\10\0\1\3\13\4\56\3\20\4"+
    "\3\0\1\3\22\0\111\3\u0107\0\11\3\1\0\45\3\10\4\1\0"+
    "\10\4\1\3\17\0\12\4\30\0\36\3\2\0\26\4\1\0\16\4"+
    "\111\0\7\3\1\0\2\3\1\0\46\3\6\4\3\0\1\4\1\0"+
    "\2\4\1\0\7\4\1\3\1\4\10\0\12\4\6\0\6\3\1\0"+
    "\2\3\1\0\40\3\5\4\1\0\2\4\1\0\5\4\1\3\7\0"+
    "\12\4\u0136\0\23\3\4\4\11\0\2\4\1\3\1\4\15\3\1\0"+
    "\42\3\7\4\3\0\5\4\15\0\12\4\126\0\1\3\54\0\4\3"+
    "\37\0\u039a\3\146\0\157\3\21\0\304\3\u0a4c\0\141\3\17\0\u0430\3"+
    "\21\4\6\3\17\4\u0faa\0\u0247\3\u21b9\0\u0239\3\7\0\37\3\1\0"+
    "\12\4\6\0\117\3\1\0\12\4\6\0\36\3\2\0\5\4\13\0"+
    "\60\3\7\4\11\0\4\3\14\0\12\4\11\0\25\3\5\0\23\3"+
    "\u02b0\0\100\3\200\0\113\3\4\0\1\4\1\3\67\4\7\0\4\4"+
    "\15\3\100\0\2\3\1\0\1\3\1\4\13\0\2\4\16\0\u17f8\3"+
    "\10\0\u04d6\3\52\0\11\3\u22e7\0\4\3\1\0\7\3\1\0\2\3"+
    "\1\0\u0123\3\17\0\1\3\35\0\3\3\2\0\1\3\16\0\4\3"+
    "\10\0\u018c\3\u0904\0\153\3\5\0\15\3\3\0\11\3\7\0\12\3"+
    "\3\0\2\4\1\0\4\4\u125c\0\56\4\2\0\27\4\u021e\0\5\4"+
    "\3\0\26\4\2\0\7\4\36\0\4\4\224\0\3\4\u01bb\0\125\3"+
    "\1\0\107\3\1\0\2\3\2\0\1\3\2\0\2\3\2\0\4\3"+
    "\1\0\14\3\1\0\1\3\1\0\7\3\1\0\101\3\1\0\4\3"+
    "\2\0\10\3\1\0\7\3\1\0\34\3\1\0\4\3\1\0\5\3"+
    "\1\0\1\3\3\0\7\3\1\0\u0154\3\2\0\31\3\1\0\31\3"+
    "\1\0\37\3\1\0\31\3\1\0\37\3\1\0\31\3\1\0\37\3"+
    "\1\0\31\3\1\0\37\3\1\0\31\3\1\0\10\3\2\0\62\4"+
    "\u0200\0\67\4\4\0\62\4\10\0\1\4\16\0\1\4\26\0\5\4"+
    "\1\0\17\4\u0450\0\37\3\6\0\6\3\325\0\7\4\1\0\21\4"+
    "\2\0\7\4\1\0\2\4\1\0\5\4\5\0\76\3\41\0\1\4"+
    "\160\0\55\3\3\0\7\4\7\3\2\0\12\4\4\0\1\3\u0141\0"+
    "\36\3\1\4\21\0\54\3\16\4\5\0\1\3\u01d0\0\34\3\16\4"+
    "\u02e6\0\7\3\1\0\4\3\1\0\2\3\1\0\17\3\1\0\305\3"+
    "\13\0\7\4\51\0\104\3\7\4\1\3\4\0\12\4\u0356\0\1\3"+
    "\u014f\0\4\3\1\0\33\3\1\0\2\3\1\0\1\3\2\0\1\3"+
    "\1\0\12\3\1\0\4\3\1\0\1\3\1\0\1\3\6\0\1\3"+
    "\4\0\1\3\1\0\1\3\1\0\1\3\1\0\3\3\1\0\2\3"+
    "\1\0\1\3\2\0\1\3\1\0\1\3\1\0\1\3\1\0\1\3"+
    "\1\0\1\3\1\0\2\3\1\0\1\3\2\0\4\3\1\0\7\3"+
    "\1\0\4\3\1\0\4\3\1\0\1\3\1\0\12\3\1\0\21\3"+
    "\5\0\3\3\1\0\5\3\1\0\21\3\u0d34\0\12\4\u0406\0\ua6e0\3"+
    "\40\0\u103a\3\6\0\336\3\2\0\u1682\3\16\0\u1d31\3\u0c1f\0\u021e\3"+
    "\u05e2\0\u134b\3\5\0\u1060\3\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udc5b\0"+
    "\1\4\36\0\140\4\200\0\360\4\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\2\1\1\22\1\23\17\4\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\5\4"+
    "\1\35\3\4\1\32\6\4\1\36\3\4\1\37\1\40"+
    "\1\41\1\42\4\4\1\43\5\4\1\31\10\4\1\44"+
    "\3\4\1\45\3\4\1\46\2\4\1\47\10\4\1\50"+
    "\1\4\1\51\1\52\1\53\1\4\1\54\1\55\1\56"+
    "\1\57\2\4\1\0\1\60\1\61\12\0\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\223\0\142"+
    "\0\142\0\142\0\142\0\142\0\142\0\u0126\0\142\0\223"+
    "\0\142\0\142\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c"+
    "\0\u027d\0\u02ae\0\u02df\0\u0310\0\u0341\0\u0372\0\u03a3\0\u03d4"+
    "\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9\0\u04fa\0\u052b\0\142"+
    "\0\u055c\0\142\0\142\0\142\0\142\0\142\0\142\0\u058d"+
    "\0\u05be\0\u05ef\0\u0620\0\u0651\0\365\0\u0682\0\u06b3\0\u06e4"+
    "\0\365\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9\0\u080a\0\365"+
    "\0\u083b\0\u086c\0\u089d\0\142\0\142\0\142\0\142\0\u08ce"+
    "\0\u08ff\0\u0930\0\u0961\0\365\0\u0992\0\u09c3\0\u09f4\0\u0a25"+
    "\0\u0a56\0\365\0\u0a87\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c"+
    "\0\u0bad\0\u0bde\0\365\0\u0c0f\0\u0c40\0\u0c71\0\365\0\u0ca2"+
    "\0\u0cd3\0\u0d04\0\365\0\u0d35\0\u0d66\0\365\0\u0d97\0\u0dc8"+
    "\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c\0\u0ebd\0\u0eee\0\365\0\u0f1f"+
    "\0\365\0\365\0\365\0\u0f50\0\365\0\365\0\365\0\365"+
    "\0\u0f81\0\u0fb2\0\u0fe3\0\365\0\365\0\u1014\0\u1045\0\u1076"+
    "\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u116b\0\u119c\0\u11cd\0\142";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\3\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\3\6\1\34\1\35\1\6\1\3\1\36"+
    "\1\6\1\37\1\6\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\6\1\3\1\5\2\0\6\47\1\50"+
    "\46\47\1\51\1\0\2\47\62\0\1\4\61\0\1\5"+
    "\53\0\1\5\3\0\1\6\1\0\2\6\21\0\12\6"+
    "\1\0\14\6\3\0\1\6\14\0\1\52\60\0\1\53"+
    "\66\0\1\54\61\0\1\55\51\0\1\56\60\0\1\57"+
    "\45\0\1\6\1\0\2\6\21\0\1\6\1\60\4\6"+
    "\1\61\3\6\1\0\14\6\3\0\1\6\1\0\1\6"+
    "\1\0\2\6\21\0\2\6\1\62\7\6\1\0\14\6"+
    "\3\0\1\6\1\0\1\6\1\0\2\6\21\0\10\6"+
    "\1\63\1\6\1\0\14\6\3\0\1\6\1\0\1\6"+
    "\1\0\2\6\21\0\4\6\1\64\5\6\1\0\10\6"+
    "\1\65\3\6\3\0\1\6\1\0\1\6\1\0\2\6"+
    "\21\0\1\6\1\66\10\6\1\0\12\6\1\67\1\6"+
    "\3\0\1\6\1\0\1\6\1\0\2\6\21\0\12\6"+
    "\1\0\3\6\1\70\10\6\3\0\1\6\1\0\1\6"+
    "\1\0\2\6\21\0\2\6\1\71\7\6\1\0\14\6"+
    "\3\0\1\6\1\0\1\6\1\0\2\6\21\0\12\6"+
    "\1\0\1\6\1\72\12\6\3\0\1\6\1\0\1\6"+
    "\1\0\2\6\21\0\12\6\1\0\1\73\13\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\4\6\1\74"+
    "\5\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\12\6\1\0\3\6\1\75\1\6\1\76"+
    "\6\6\3\0\1\6\1\0\1\6\1\0\2\6\21\0"+
    "\10\6\1\77\1\6\1\0\1\100\13\6\3\0\1\6"+
    "\1\0\1\6\1\0\2\6\21\0\12\6\1\0\5\6"+
    "\1\101\6\6\3\0\1\6\1\0\1\6\1\0\2\6"+
    "\21\0\12\6\1\0\1\102\13\6\3\0\1\6\1\0"+
    "\1\6\1\0\2\6\21\0\12\6\1\0\13\6\1\103"+
    "\3\0\1\6\6\47\1\0\46\47\2\0\2\47\6\0"+
    "\1\104\20\0\1\105\1\106\1\0\1\107\27\0\1\6"+
    "\1\0\2\6\21\0\2\6\1\110\7\6\1\0\14\6"+
    "\3\0\1\6\1\0\1\6\1\0\2\6\21\0\7\6"+
    "\1\111\2\6\1\0\14\6\3\0\1\6\1\0\1\6"+
    "\1\0\2\6\21\0\12\6\1\0\1\6\1\112\12\6"+
    "\3\0\1\6\1\0\1\6\1\0\2\6\21\0\1\6"+
    "\1\113\10\6\1\0\14\6\3\0\1\6\1\0\1\6"+
    "\1\0\2\6\21\0\1\6\1\114\10\6\1\0\14\6"+
    "\3\0\1\6\1\0\1\6\1\0\2\6\21\0\12\6"+
    "\1\0\5\6\1\115\6\6\3\0\1\6\1\0\1\6"+
    "\1\0\2\6\21\0\3\6\1\116\6\6\1\0\14\6"+
    "\3\0\1\6\1\0\1\6\1\0\2\6\21\0\7\6"+
    "\1\117\2\6\1\0\14\6\3\0\1\6\1\0\1\6"+
    "\1\0\2\6\21\0\12\6\1\0\4\6\1\120\7\6"+
    "\3\0\1\6\1\0\1\6\1\0\2\6\21\0\12\6"+
    "\1\0\1\121\13\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\12\6\1\0\7\6\1\122\4\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\12\6\1\0"+
    "\5\6\1\123\6\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\7\6\1\124\2\6\1\0\14\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\12\6\1\0"+
    "\10\6\1\125\3\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\12\6\1\0\3\6\1\126\10\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\3\6\1\127"+
    "\6\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\3\6\1\130\6\6\1\0\14\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\3\6\1\131"+
    "\6\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\1\6\1\132\10\6\1\0\14\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\10\6\1\133"+
    "\1\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\12\6\1\0\1\6\1\134\12\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\1\6\1\135"+
    "\10\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\1\6\1\136\10\6\1\0\14\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\10\6\1\137"+
    "\1\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\12\6\1\0\3\6\1\140\10\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\12\6\1\0"+
    "\3\6\1\141\10\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\7\6\1\142\2\6\1\0\14\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\10\6\1\143"+
    "\1\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\12\6\1\0\5\6\1\144\6\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\7\6\1\145"+
    "\2\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\12\6\1\0\7\6\1\146\4\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\12\6\1\0"+
    "\3\6\1\147\10\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\4\6\1\150\5\6\1\0\14\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\10\6\1\151"+
    "\1\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\2\6\1\152\7\6\1\0\14\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\3\6\1\153"+
    "\6\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\12\6\1\0\6\6\1\154\5\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\3\6\1\155"+
    "\6\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\10\6\1\156\1\6\1\0\14\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\7\6\1\157"+
    "\2\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\12\6\1\0\1\6\1\160\12\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\10\6\1\161"+
    "\1\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\10\6\1\162\1\6\1\0\14\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\5\6\1\163"+
    "\4\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\11\6\1\164\1\0\14\6\3\0\1\6"+
    "\1\0\1\6\1\0\2\6\21\0\4\6\1\165\5\6"+
    "\1\0\14\6\3\0\1\6\1\0\1\6\1\0\2\6"+
    "\21\0\12\6\1\0\6\6\1\166\5\6\3\0\1\6"+
    "\1\0\1\6\1\0\2\6\21\0\12\6\1\0\13\6"+
    "\1\167\3\0\1\6\1\0\1\6\1\0\2\6\21\0"+
    "\12\6\1\0\6\6\1\170\5\6\3\0\1\6\1\0"+
    "\1\6\1\0\2\6\21\0\12\6\1\0\5\6\1\171"+
    "\6\6\3\0\1\6\1\0\1\6\1\0\2\6\21\0"+
    "\12\6\1\0\3\6\1\172\10\6\3\0\1\6\1\0"+
    "\1\6\1\0\2\6\21\0\12\6\1\173\14\6\3\0"+
    "\1\6\1\0\1\6\1\0\2\6\21\0\4\6\1\174"+
    "\5\6\1\0\14\6\3\0\1\6\1\0\1\6\1\0"+
    "\2\6\21\0\1\6\1\175\10\6\1\0\14\6\3\0"+
    "\1\6\41\0\1\176\61\0\1\177\45\0\1\200\71\0"+
    "\1\201\63\0\1\202\45\0\1\203\61\0\1\204\61\0"+
    "\1\205\55\0\1\206\75\0\1\207\46\0\1\210\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4606];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\4\1\6\11\1\1\1\11\1\1\2\11"+
    "\25\1\1\11\1\1\6\11\24\1\4\11\63\1\1\0"+
    "\2\1\12\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[136];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuilder string = new StringBuilder();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3866) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              Errors.fatal(yyline+1, yycolumn,
			"String was never closed! " + string.toString() 
		);
            }  // fall though
            case 137: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { Errors.fatal(yyline+1, yycolumn,
		"ignoring illegal character: " + yytext()
	);
            } 
            // fall through
          case 51: break;
          case 2: 
            { try {
			int val = Integer.parseInt(yytext());
			Symbol S = new Symbol(sym.INTLITERAL,
				new IntLitTokenVal(yyline+1, yycolumn, val)
			);

			return S;

		} catch(NumberFormatException e) {
			Errors.warn(yyline+1, yycolumn, "Value out of bounds!");
		}
            } 
            // fall through
          case 52: break;
          case 3: 
            { yycolumn += yytext().length();
            } 
            // fall through
          case 53: break;
          case 4: 
            { String val = yytext();
		Symbol S = new Symbol(sym.ID, new IdentifierTokenValue(yyline+1, yycolumn, val));
		return S;
            } 
            // fall through
          case 54: break;
          case 5: 
            { Symbol S = new Symbol(sym.MINUS, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 55: break;
          case 6: 
            { string.setLength(0); yybegin(STRING);
            } 
            // fall through
          case 56: break;
          case 7: 
            { Symbol S = new Symbol(sym.LCURLY, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 57: break;
          case 8: 
            { Symbol S = new Symbol(sym.RCURLY, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 58: break;
          case 9: 
            { Symbol S = new Symbol(sym.LPAREN, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 59: break;
          case 10: 
            { Symbol S = new Symbol(sym.RPAREN, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 60: break;
          case 11: 
            { Symbol S = new Symbol(sym.COMMA, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 61: break;
          case 12: 
            { Symbol S = new Symbol(sym.ASSIGN, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 62: break;
          case 13: 
            { Symbol S = new Symbol(sym.SEMICOLON, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 63: break;
          case 14: 
            { Symbol S = new Symbol(sym.PLUS, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 64: break;
          case 15: 
            { Symbol S = new Symbol(sym.TIMES, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 65: break;
          case 16: 
            { Symbol S = new Symbol(sym.DIVIDE, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 66: break;
          case 17: 
            { Symbol S = new Symbol(sym.NOT, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 67: break;
          case 18: 
            { Symbol S = new Symbol(sym.LESS, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 68: break;
          case 19: 
            { Symbol S = new Symbol(sym.GREATER, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 69: break;
          case 20: 
            { string.append(yytext());
            } 
            // fall through
          case 70: break;
          case 21: 
            { yybegin(YYINITIAL); 
		Symbol S = new Symbol(
			sym.STRINGLITERAL,
			new StringTokenValue(yyline+1, yycolumn, string.toString())
		); 
		return S;
            } 
            // fall through
          case 71: break;
          case 22: 
            { string.append('\\');
            } 
            // fall through
          case 72: break;
          case 23: 
            { Symbol S = new Symbol(sym.EQUALS, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 73: break;
          case 24: 
            { Symbol S = new Symbol(sym.NOTEQUALS, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 74: break;
          case 25: 
            { Symbol S = new Symbol(sym.AND, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 75: break;
          case 26: 
            { Symbol S = new Symbol(sym.OR, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 76: break;
          case 27: 
            { Symbol S = new Symbol(sym.LESSEQ, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 77: break;
          case 28: 
            { Symbol S = new Symbol(sym.GREATEREQ, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 78: break;
          case 29: 
            { Symbol S = new Symbol(sym.IF, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 79: break;
          case 30: 
            { Symbol S = new Symbol(sym.DO, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 80: break;
          case 31: 
            { string.append('\"');
            } 
            // fall through
          case 81: break;
          case 32: 
            { string.append('\t');
            } 
            // fall through
          case 82: break;
          case 33: 
            { string.append('\r');
            } 
            // fall through
          case 83: break;
          case 34: 
            { string.append('\n');
            } 
            // fall through
          case 84: break;
          case 35: 
            { Symbol S = new Symbol(sym.INT, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 85: break;
          case 36: 
            { Symbol S = new Symbol(sym.TRUE, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 86: break;
          case 37: 
            { Symbol S = new Symbol(sym.ELSE, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 87: break;
          case 38: 
            { Symbol S = new Symbol(sym.CASE, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 88: break;
          case 39: 
            { Symbol S = new Symbol(sym.VOID, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 89: break;
          case 40: 
            { Symbol S = new Symbol(sym.CLASS, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 90: break;
          case 41: 
            { Symbol S = new Symbol(sym.FALSE, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 91: break;
          case 42: 
            { Symbol S = new Symbol(sym.WHILE, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 92: break;
          case 43: 
            { Symbol S = new Symbol(sym.STRING, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 93: break;
          case 44: 
            { Symbol S = new Symbol(sym.RETURN, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 94: break;
          case 45: 
            { Symbol S = new Symbol(sym.STATIC, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 95: break;
          case 46: 
            { Symbol S = new Symbol(sym.SWITCH, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 96: break;
          case 47: 
            { Symbol S = new Symbol(sym.PUBLIC, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 97: break;
          case 48: 
            { Symbol S = new Symbol(sym.BOOLEAN, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 98: break;
          case 49: 
            { Symbol S = new Symbol(sym.DEFAULT, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 99: break;
          case 50: 
            { Symbol S = new Symbol(sym.SYSTEM_OUT, new TokenVal(yyline+1, yycolumn));
		return S;
            } 
            // fall through
          case 100: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
